# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [3]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [7]:
mat1 = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat2 = np.array([[41,42,43],[51,52,53],[61,62,63]])
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat2/mat1)

print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))



1st Matrix of random single-digit numbers
----------------------------------------
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[41 42 43]
 [51 52 53]
 [61 62 63]]

Addition
------------------
 [[52 54 56]
 [72 74 76]
 [92 94 96]]

Multiplication
------------------
 [[ 451  504  559]
 [1071 1144 1219]
 [1891 1984 2079]]

Division
------------------
 [[3.72727273 3.5        3.30769231]
 [2.42857143 2.36363636 2.30434783]
 [1.96774194 1.9375     1.90909091]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-49 -48 -47]
 [-39 -38 -37]
 [-29 -28 -27]]

Addition of a scalar (100)
-------------------------
 [[111 112 113]
 [121 122 123]
 [131 132 133]]

Exponentiation, matrix cubed here
----------------------------------------
 [[ 1331  1728  2197]
 [ 9261 10648 12167]
 [29791 32768 35937]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[3.31662479 3.

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [8]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 8 4]
 [7 2 9]
 [7 2 5]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 2 7]
 [5 9 6]
 [4 7 3]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 49

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [19 12 18]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [17 18 14]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [160 126  70]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 20 126 126]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.444444444444445

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [11]:
##Solution
from numpy.random import randint as ri
mat1 = np.array(ri(1,100,9)).reshape(9,1)
mat1

array([[91],
       [11],
       [11],
       [ 8],
       [41],
       [59],
       [75],
       [50],
       [56]])

### 4.Sort

In [12]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [55 94 71 31 53 59 29 37 44 14]

Here is the sorted vector
 -------------------------------------------------- 
 [14 29 31 37 44 53 55 59 71 94]


In [13]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[16 51 50 93 35]
 [69 25 86  2 49]
 [99  5 76 67 21]
 [62 19 61  7 59]
 [55 93 65 37 71]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[16 35 50 51 93]
 [ 2 25 49 69 86]
 [ 5 21 67 76 99]
 [ 7 19 59 61 62]
 [37 55 65 71 93]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[16  5 50  2 21]
 [55 19 61  7 35]
 [62 25 65 37 49]
 [69 51 76 67 59]
 [99 93 86 93 71]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [14]:
from numpy.random import randint as ri
a=ri(1,100,10)
b=ri(5,50,10)
c=ri(7,200,10)
print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:", b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

print("Max of a:", a.min())
print("Max of b:", b.min())


print("Max of a location:", a.argmin())
print("Max of b location:", b.argmin())
print("Max of c location:", b.argmin())



a: [26  8  5 98 83 30  4 52 14 49]
b: [35 23  5 25 43 37 43 19  5 24]
c: [174 146  99 157  53  38 110 129 173 128]
Max of a: 98
Max of b: 43
Max of a location: 3
Max of b location: 4
Max of c location: 4
Max of a: 4
Max of b: 5
Max of a location: 6
Max of b location: 2
Max of c location: 2


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [15]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))


1st Matrix of random single-digit numbers
----------------------------------------
 [[5 1 9]
 [2 8 9]
 [7 6 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 9 7]
 [9 3 6]
 [7 3 8]]

Sq-root of 1st matrix using np
------------------
 [[2.23606798 1.         3.        ]
 [1.41421356 2.82842712 3.        ]
 [2.64575131 2.44948974 2.82842712]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 2.71828183e+00 8.10308393e+03]
 [7.38905610e+00 2.98095799e+03 8.10308393e+03]
 [1.09663316e+03 4.03428793e+02 2.98095799e+03]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.         0.95424251]
 [0.30103    0.90308999 0.95424251]
 [0.84509804 0.77815125 0.90308999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[5 1 2]
 [2 2 3]
 [0 0 0]]


### 7.Generating matrices from distributions

In [16]:
import numpy as np
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.36709488 0.39730471 0.46452076]
 [0.99032867 0.56150077 0.46519327]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.61664276  0.15134393  0.04593254]
 [ 1.22895202 -1.29953462  0.12106339]
 [-1.5196831   0.07613299  0.21611132]
 [-0.09632176  0.69142102  2.07901237]]
Random integer vector: [20 45 59 67  3 46 16 74 70  8]

Random integer matrix
[[28 81 61 81]
 [47 57 17  2]
 [50 49 96 44]
 [66 83 73 42]]

20 samples drawn from a dice throw: [2 4 6 3 3 3 3 6 5 3 5 3 6 1 2 3 5 3 1 1]


### 8.Find the nearest value from a given number in an array using NumPy.

In [17]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

import numpy as np
x = np.random.uniform(1, 12, 5)
print(x)
print("\nInput array\n","-"*50,"\n",x)
v = 4
n = x[np.abs(x - v).argmin()]
print(n)

[ 4.795184    7.6987016   3.82598911 10.72703281  5.03414687]

Input array
 -------------------------------------------------- 
 [ 4.795184    7.6987016   3.82598911 10.72703281  5.03414687]
3.825989110902692


In [18]:
x.flat[3]

10.72703281175856

### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [19]:
import numpy as np
print(np.fromfunction(lambda i, j: i*j, (3, 3), dtype=int))

[[0 0 0]
 [0 1 2]
 [0 2 4]]
